CREATE TABLE IF NOT EXISTS cometidos_funcionarios_informes (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  cometido_funcionario_id BIGINT UNSIGNED NOT NULL,
  estado_informe VARCHAR(80) NOT NULL DEFAULT 'borrador',
  fecha_desde_real DATE NULL,
  fecha_hasta_real DATE NULL,
  hora_salida_real TIME NULL,
  hora_regreso_real TIME NULL,
  justificacion_cambio_fechas TEXT NULL,
  organismos_autoridades_relatores TEXT NULL,
  descripcion_actividades_realizadas LONGTEXT NULL,
  resultados_obtenidos LONGTEXT NULL,
  opiniones_propuestas LONGTEXT NULL,
  requiere_nuevo_cometido_diferencia TINYINT(1) NOT NULL DEFAULT 0,
  fecha_envio TIMESTAMP NULL,
  user_id_envia BIGINT UNSIGNED NULL,
  observacion_sistema TEXT NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  PRIMARY KEY (id),
  KEY com_inf_com_estado_idx (cometido_funcionario_id, estado_informe),
  CONSTRAINT com_inf_com_fk FOREIGN KEY (cometido_funcionario_id) REFERENCES cometidos_funcionarios(id) ON DELETE CASCADE,
  CONSTRAINT com_inf_user_fk FOREIGN KEY (user_id_envia) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
