-- Apoyo manual phpMyAdmin si no se ejecuta migrate.
-- Ejecutar por partes y revisar existencia de columnas/tablas antes de aplicar en producción.

ALTER TABLE `cometidos_funcionarios`
  ADD COLUMN `origen_cometido` VARCHAR(40) NOT NULL DEFAULT 'establecimiento',
  ADD COLUMN `funcionario_ac_autorizado_id` BIGINT UNSIGNED NULL,
  ADD COLUMN `numero_cometido_interno` VARCHAR(60) NULL,
  ADD COLUMN `region_origen` VARCHAR(20) NULL,
  ADD COLUMN `comuna_origen_id` BIGINT UNSIGNED NULL,
  ADD COLUMN `comuna_origen_nombre` VARCHAR(255) NULL,
  ADD COLUMN `es_destino_extranjero` TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN `pais_destino` VARCHAR(120) NULL,
  ADD COLUMN `ciudad_destino_extranjero` VARCHAR(160) NULL,
  ADD COLUMN `subdireccion_dependencia_ac` VARCHAR(255) NULL,
  ADD COLUMN `unidad_departamento_ac` VARCHAR(255) NULL,
  ADD COLUMN `es_jefatura_ac` TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN `estado_autorizacion_jefatura_ac` VARCHAR(80) NULL,
  ADD COLUMN `jefatura_autorizadora_ac_id` BIGINT UNSIGNED NULL,
  ADD COLUMN `jefatura_autorizadora_user_id` BIGINT UNSIGNED NULL,
  ADD COLUMN `autorizado_por_subrogante` TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN `fecha_autorizacion_jefatura_ac` TIMESTAMP NULL,
  ADD COLUMN `observacion_jefatura_ac` TEXT NULL,
  ADD COLUMN `requiere_pasaje_aereo` TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN `dias_habiles_anticipacion` INT NULL,
  ADD COLUMN `justificacion_menor_7_dias` TEXT NULL;

CREATE TABLE IF NOT EXISTS `cometido_funcionario_documentos_generados` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cometido_funcionario_id` BIGINT UNSIGNED NOT NULL,
  `tipo_documento` VARCHAR(80) NOT NULL,
  `numero_documento` VARCHAR(80) NULL,
  `codigo_validacion` VARCHAR(80) NOT NULL,
  `token_validacion` VARCHAR(120) NOT NULL,
  `documento_hash` VARCHAR(128) NULL,
  `archivo_pdf_path` VARCHAR(500) NULL,
  `estado` VARCHAR(40) NOT NULL DEFAULT 'vigente',
  `emitido_por_user_id` BIGINT UNSIGNED NULL,
  `emitido_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `cfg_doc_codigo_uq` (`codigo_validacion`),
  UNIQUE KEY `cfg_doc_token_uq` (`token_validacion`),
  KEY `cfg_doc_com_tipo_idx` (`cometido_funcionario_id`, `tipo_documento`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `cometido_funcionario_firmas` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cometido_funcionario_id` BIGINT UNSIGNED NOT NULL,
  `documento_generado_id` BIGINT UNSIGNED NULL,
  `user_id` BIGINT UNSIGNED NULL,
  `funcionario_ac_autorizado_id` BIGINT UNSIGNED NULL,
  `tipo_firma` VARCHAR(80) NOT NULL,
  `rol_firmante` VARCHAR(80) NULL,
  `nombre_firmante` VARCHAR(255) NULL,
  `rut_firmante` VARCHAR(40) NULL,
  `cargo_firmante` VARCHAR(255) NULL,
  `dependencia_firmante` VARCHAR(255) NULL,
  `es_subrogante` TINYINT(1) NOT NULL DEFAULT 0,
  `ip_firma` VARCHAR(80) NULL,
  `user_agent` TEXT NULL,
  `fecha_firma` TIMESTAMP NULL,
  `token_firma` VARCHAR(120) NOT NULL,
  `hash_firma` VARCHAR(128) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `cfg_firma_token_uq` (`token_firma`),
  KEY `cfg_firma_tipo_idx` (`cometido_funcionario_id`, `tipo_firma`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `cometido_funcionario_pasajes_aereos` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cometido_funcionario_id` BIGINT UNSIGNED NOT NULL,
  `numero_solicitud_pedido` VARCHAR(80) NULL,
  `solicitud_pedido_pdf_path` VARCHAR(500) NULL,
  `estado_pasaje` VARCHAR(80) NOT NULL DEFAULT 'pendiente_reserva',
  `reserva_usuario_id` BIGINT UNSIGNED NULL,
  `reserva_archivo_path` VARCHAR(500) NULL,
  `reserva_nombre_original` VARCHAR(255) NULL,
  `reserva_fecha` TIMESTAMP NULL,
  `reserva_observacion` TEXT NULL,
  `cdp_usuario_id` BIGINT UNSIGNED NULL,
  `cdp_referencia` VARCHAR(255) NULL,
  `cdp_fecha` DATE NULL,
  `cdp_archivo_path` VARCHAR(500) NULL,
  `cdp_nombre_original` VARCHAR(255) NULL,
  `cdp_observacion` TEXT NULL,
  `compra_usuario_id` BIGINT UNSIGNED NULL,
  `proveedor` VARCHAR(255) NULL,
  `monto` BIGINT UNSIGNED NULL,
  `fecha_compra` DATE NULL,
  `numero_oc` VARCHAR(100) NULL,
  `compra_archivo_path` VARCHAR(500) NULL,
  `compra_nombre_original` VARCHAR(255) NULL,
  `compra_observacion` TEXT NULL,
  `boleto_disponible_at` TIMESTAMP NULL,
  `notificado_funcionario_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `cfg_pasaje_cometido_uq` (`cometido_funcionario_id`),
  UNIQUE KEY `cfg_pasaje_num_sp_uq` (`numero_solicitud_pedido`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
