@extends('layouts.app')
@section('content')
<div class="container py-3" style="max-width:850px"><a href="{{ route('votaciones.operacion.index') }}" class="text-decoration-none">← Mis grupos</a><div class="card shadow-sm mt-3 mb-3"><div class="card-body"><div class="d-flex justify-content-between gap-2"><div><small class="text-muted">{{ $grupo->jornada->nombre }}</small><h1 class="h3 mb-1">{{ $grupo->nombre }}</h1><span class="badge text-bg-primary">{{ str($grupo->estado)->replace('_',' ')->title() }}</span></div>@if($grupo->estado==='pendiente')<form method="POST" action="{{ route('votaciones.operacion.grupos.iniciar',$grupo) }}">@csrf<button class="btn btn-success btn-lg" onclick="return confirm('¿Iniciar el recorrido?')">Iniciar grupo</button></form>@endif</div></div></div>@include('votaciones.partials.alertas')
<div class="vstack gap-3">@foreach($grupo->rutas as $ruta)@php($estado=$ruta->visita?->estado??'pendiente')<article class="card {{ $estado==='en_votacion'?'border-success border-2':($estado==='en_traslado'?'border-primary':'') }}"><div class="card-body"><div class="d-flex justify-content-between"><div><span class="badge text-bg-{{ $estado==='finalizada'?'success':($estado==='en_votacion'?'success':($estado==='en_traslado'?'primary':'secondary')) }}">{{ $ruta->orden }} · {{ str($estado)->replace('_',' ')->title() }}</span><h2 class="h5 mt-2 mb-1">{{ $ruta->establecimiento->nombre_establecimiento }}</h2><div class="text-muted">RBD {{ $ruta->establecimiento->rbd }} · {{ $ruta->establecimiento->comuna }}</div></div></div>
@if($estado==='en_traslado')<form method="POST" action="{{ route('votaciones.operacion.rutas.iniciar',$ruta) }}" class="mt-3">@csrf<label class="form-label">Hora de inicio</label><div class="input-group"><input class="form-control" type="datetime-local" name="fecha_hora" value="{{ now(config('votaciones.timezone'))->format('Y-m-d\TH:i') }}"><button class="btn btn-success btn-lg">Iniciar votación</button></div></form>@elseif($estado==='en_votacion')<form method="POST" action="{{ route('votaciones.operacion.rutas.finalizar',$ruta) }}" class="mt-3">@csrf<label class="form-label">Hora de término</label><div class="input-group"><input class="form-control" type="datetime-local" name="fecha_hora" value="{{ now(config('votaciones.timezone'))->format('Y-m-d\TH:i') }}"><button class="btn btn-danger btn-lg" onclick="return confirm('¿Finalizar esta votación?')">Finalizar</button></div></form>@elseif($estado==='finalizada')<div class="small text-success mt-2">{{ $ruta->visita->inicio_votacion_at?->format('H:i') }} – {{ $ruta->visita->fin_votacion_at?->format('H:i') }}</div>@endif</div></article>@endforeach</div>
<div class="card shadow-sm mt-4"><div class="card-header"><strong>Reportar incidencia</strong></div><form method="POST" action="{{ route('votaciones.operacion.incidencias.store',$grupo) }}"><div class="card-body row g-3">@csrf<div class="col-md-6"><label class="form-label">Tipo</label><select class="form-select" name="tipo" required>@foreach(config('votaciones.tipos_incidencia') as $key=>$label)<option value="{{ $key }}">{{ $label }}</option>@endforeach</select></div><div class="col-md-6"><label class="form-label">Establecimiento (opcional)</label><select class="form-select" name="ruta_votacion_id"><option value="">General</option>@foreach($grupo->rutas as $ruta)<option value="{{ $ruta->id }}">{{ $ruta->establecimiento->nombre_establecimiento }}</option>@endforeach</select></div><div class="col-12"><label class="form-label">Detalle interno</label><textarea class="form-control" name="detalle_interno" required maxlength="2000"></textarea><div class="form-text">Este texto nunca se publica.</div></div><div class="col-12 form-check ms-2"><input class="form-check-input" type="checkbox" name="publica" value="1" id="publica"><label class="form-check-label" for="publica">Mostrar esta incidencia en el tablero público</label></div><div class="col-12"><label class="form-label">Mensaje público (obligatorio si se publica)</label><textarea class="form-control" name="mensaje_publico" maxlength="1000" placeholder="Información breve, sin nombres ni datos personales"></textarea></div></div><div class="card-footer text-end"><button class="btn btn-warning">Registrar incidencia</button></div></form></div>
</div>
@endsection
@push('scripts')
<script>
document.addEventListener('DOMContentLoaded', () => {
    document.querySelectorAll('form[action*="/gestion/votaciones/operacion/"]').forEach((form) => {
        form.addEventListener('submit', () => {
            form.querySelectorAll('button[type="submit"], button:not([type])').forEach((button) => {
                button.disabled = true;
                button.setAttribute('aria-busy', 'true');
            });
        }, { once: true });
    });
});
</script>
@endpush
