<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Regiones de Chile (códigos 01..16)
    |--------------------------------------------------------------------------
    | Usadas para poblar el <select> de Región.
    */
    'regiones' => [
        '01' => 'Región de Tarapacá',
        '02' => 'Región de Antofagasta',
        '03' => 'Región de Atacama',
        '04' => 'Región de Coquimbo',
        '05' => 'Región de Valparaíso',
        '06' => "Región del Libertador Gral. Bernardo O'Higgins",
        '07' => 'Región del Maule',
        '08' => 'Región del Biobío',
        '09' => 'Región de La Araucanía',
        '10' => 'Región de Los Lagos',
        '11' => 'Región de Aysén del Gral. C. Ibáñez del Campo',
        '12' => 'Región de Magallanes y de la Antártica Chilena',
        '13' => 'Región Metropolitana de Santiago',
        '14' => 'Región de Los Ríos',
        '15' => 'Región de Arica y Parinacota',
        '16' => 'Región de Ñuble',
    ],

    /*
    |--------------------------------------------------------------------------
    | Comunas habilitadas para postulación y búsqueda de postulantes
    |--------------------------------------------------------------------------
    | Se usan para filtros de comuna en buscadores y para la selección
    | de lugares de desempeño del postulante.
    */
    'comunas_postulacion_permitidas' => [
        'Coronel',
        'Lota',
        'San Pedro de la Paz',
        'Santa Juana',
        'Isla Santa María',
    ],

    /*
    |--------------------------------------------------------------------------
    | Comunas por región (completo)
    |--------------------------------------------------------------------------
    | Lo usa el seeder para poblar la tabla "communes" con (name, region_code).
    */
    'comunas_por_region' => [
        '01' => [ // Tarapacá
            'Iquique',
            'Alto Hospicio',
            'Pozo Almonte',
            'Camiña',
            'Colchane',
            'Huara',
            'Pica',
        ],
        '02' => [ // Antofagasta
            'Antofagasta',
            'Mejillones',
            'Sierra Gorda',
            'Taltal',
            'Calama',
            'Ollagüe',
            'San Pedro de Atacama',
            'Tocopilla',
            'María Elena',
        ],
        '03' => [ // Atacama
            'Copiapó',
            'Caldera',
            'Tierra Amarilla',
            'Chañaral',
            'Diego de Almagro',
            'Vallenar',
            'Alto del Carmen',
            'Freirina',
            'Huasco',
        ],
        '04' => [ // Coquimbo
            'La Serena',
            'Coquimbo',
            'Andacollo',
            'La Higuera',
            'Paihuano',
            'Vicuña',
            'Ovalle',
            'Combarbalá',
            'Monte Patria',
            'Punitaqui',
            'Río Hurtado',
            'Illapel',
            'Canela',
            'Los Vilos',
            'Salamanca',
        ],
        '05' => [ // Valparaíso
            'Valparaíso',
            'Viña del Mar',
            'Concón',
            'Quilpué',
            'Villa Alemana',
            'Casablanca',
            'Juan Fernández',
            'Puchuncaví',
            'Quintero',
            'San Antonio',
            'Cartagena',
            'El Quisco',
            'El Tabo',
            'Algarrobo',
            'Santo Domingo',
            'San Felipe',
            'Catemu',
            'Llaillay',
            'Panquehue',
            'Putaendo',
            'Santa María',
            'Los Andes',
            'Calle Larga',
            'Rinconada',
            'San Esteban',
            'Quillota',
            'La Calera',
            'La Cruz',
            'Hijuelas',
            'Nogales',
            'Petorca',
            'Cabildo',
            'Papudo',
            'Zapallar',
            'La Ligua',
            'Isla de Pascua',
        ],
        '06' => [ // O'Higgins
            'Rancagua',
            'Machalí',
            'Graneros',
            'Mostazal',
            'Doñihue',
            'Coltauco',
            'Quinta de Tilcoco',
            'Rengo',
            'Requínoa',
            'Olivar',
            'Malloa',
            'Coinco',
            'Peumo',
            'Pichidegua',
            'San Vicente',
            'Pichilemu',
            'Marchihue',
            'La Estrella',
            'Litueche',
            'Navidad',
            'Paredones',
            'San Fernando',
            'Chimbarongo',
            'Nancagua',
            'Placilla',
            'Santa Cruz',
            'Lolol',
            'Palmilla',
            'Peralillo',
            'Pumanque',
        ],
        '07' => [ // Maule
            'Talca',
            'San Clemente',
            'Pelarco',
            'Pencahue',
            'Maule',
            'San Rafael',
            'Curepto',
            'Empedrado',
            'Constitución',
            'Río Claro',
            'Linares',
            'Yerbas Buenas',
            'Colbún',
            'Longaví',
            'Parral',
            'Retiro',
            'Cauquenes',
            'Pelluhue',
            'Chanco',
            'Curicó',
            'Teno',
            'Romeral',
            'Rauco',
            'Sagrada Familia',
            'Hualañé',
            'Licantén',
            'Vichuquén',
            'Molina',
        ],
        '08' => [ // Biobío
            'Concepción',
            'Talcahuano',
            'Hualpén',
            'San Pedro de la Paz',
            'Chiguayante',
            'Penco',
            'Tomé',
            'Coronel',
            'Lota',
            'Santa Juana',
            'Hualqui',
            'Florida',
            'Cabrero',
            'Yumbel',
            'Los Ángeles',
            'Nacimiento',
            'Laja',
            'San Rosendo',
            'Mulchén',
            'Negrete',
            'Quilaco',
            'Quilleco',
            'Tucapel',
            'Antuco',
            'Alto Biobío',
            'Arauco',
            'Curanilahue',
            'Lebu',
            'Los Álamos',
            'Cañete',
            'Tirúa',
        ],
        '09' => [ // La Araucanía
            'Temuco',
            'Padre Las Casas',
            'Cunco',
            'Melipeuco',
            'Vilcún',
            'Freire',
            'Pitrufquén',
            'Gorbea',
            'Loncoche',
            'Toltén',
            'Teodoro Schmidt',
            'Puerto Saavedra',
            'Carahue',
            'Nueva Imperial',
            'Cholchol',
            'Lautaro',
            'Perquenco',
            'Galvarino',
            'Traiguén',
            'Victoria',
            'Curacautín',
            'Lonquimay',
            'Angol',
            'Renaico',
            'Collipulli',
            'Ercilla',
            'Purén',
            'Los Sauces',
            'Lumaco',
        ],
        '10' => [ // Los Lagos
            'Puerto Montt',
            'Puerto Varas',
            'Llanquihue',
            'Frutillar',
            'Maullín',
            'Calbuco',
            'Cochamó',
            'Fresia',
            'Los Muermos',
            'Osorno',
            'San Juan de la Costa',
            'San Pablo',
            'Puyehue',
            'Río Negro',
            'Purranque',
            'Puerto Octay',
            'Castro',
            'Ancud',
            'Quellón',
            'Dalcahue',
            'Chonchi',
            'Curaco de Vélez',
            'Quinchao',
            'Queilén',
            'Quemchi',
            'Hualaihué',
            'Chaitén',
            'Futaleufú',
            'Palena',
        ],
        '11' => [ // Aysén
            'Coyhaique',
            'Lago Verde',
            'Aysén',
            'Cisnes',
            'Guaitecas',
            'Cochrane',
            'O’Higgins',
            'Tortel',
            'Chile Chico',
            'Río Ibáñez',
        ],
        '12' => [ // Magallanes
            'Punta Arenas',
            'Río Verde',
            'Laguna Blanca',
            'San Gregorio',
            'Porvenir',
            'Primavera',
            'Timaukel',
            'Puerto Natales',
            'Torres del Paine',
            'Cabo de Hornos',
            'Antártica',
        ],
        '13' => [ // Metropolitana
            'Santiago',
            'Providencia',
            'Las Condes',
            'Vitacura',
            'Lo Barnechea',
            'La Reina',
            'Ñuñoa',
            'Peñalolén',
            'Macul',
            'La Florida',
            'Puente Alto',
            'Pirque',
            'San José de Maipo',
            'La Granja',
            'La Pintana',
            'San Ramón',
            'El Bosque',
            'San Bernardo',
            'Buin',
            'Paine',
            'Calera de Tango',
            'Estación Central',
            'Cerrillos',
            'Maipú',
            'Pudahuel',
            'Lo Prado',
            'Cerro Navia',
            'Quinta Normal',
            'Renca',
            'Independencia',
            'Recoleta',
            'Conchalí',
            'Huechuraba',
            'Quilicura',
            'Lampa',
            'Colina',
            'Tiltil',
            'Melipilla',
            'María Pinto',
            'Curacaví',
            'Alhué',
            'Peñaflor',
            'Talagante',
            'El Monte',
            'Isla de Maipo',
            'Padre Hurtado',
            'San Pedro',
        ],
        '14' => [ // Los Ríos
            'Valdivia',
            'Corral',
            'Lanco',
            'Los Lagos',
            'Máfil',
            'Mariquina',
            'Paillaco',
            'Panguipulli',
            'La Unión',
            'Río Bueno',
            'Lago Ranco',
            'Futrono',
        ],
        '15' => [ // Arica y Parinacota
            'Arica',
            'Camarones',
            'Putre',
            'General Lagos',
        ],
        '16' => [ // Ñuble
            'Chillán',
            'Chillán Viejo',
            'Pinto',
            'Coihueco',
            'San Ignacio',
            'El Carmen',
            'Pemuco',
            'Yungay',
            'Quillón',
            'Bulnes',
            'San Nicolás',
            'San Carlos',
            'Ñiquén',
            'San Fabián',
            'Coelemu',
            'Trehuaco',
            'Ránquil',
            'Portezuelo',
            'Cobquecura',
            'Ninhue',
            'Quirihue',
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Nacionalidades con emoji (opcional, referencia rápida)
    |--------------------------------------------------------------------------
    | La vista usa el método nacionalidades() del controlador; esto es opcional.
    */
    'nacionalidades_emoji' => [
        'Chile' => '🇨🇱 Chile',
        'Argentina' => '🇦🇷 Argentina',
        'Perú' => '🇵🇪 Perú',
        'Bolivia' => '🇧🇴 Bolivia',
        'Brasil' => '🇧🇷 Brasil',
        'Uruguay' => '🇺🇾 Uruguay',
        'Paraguay' => '🇵🇾 Paraguay',
        'Colombia' => '🇨🇴 Colombia',
        'Venezuela' => '🇻🇪 Venezuela',
        'Ecuador' => '🇪🇨 Ecuador',
        'México' => '🇲🇽 México',
        'España' => '🇪🇸 España',
        'Estados Unidos' => '🇺🇸 Estados Unidos',
        'Italia' => '🇮🇹 Italia',
        'Francia' => '🇫🇷 Francia',
        'Alemania' => '🇩🇪 Alemania',
        'China' => '🇨🇳 China',
        'Japón' => '🇯🇵 Japón',
        'Corea del Sur' => '🇰🇷 Corea del Sur',
    ],
];
