<?php

return [
    'base_calculo' => 'total_haberes',
    'fallback_base_calculo' => [
        'monto_tributable',
        'monto_imponible',
    ],
    'topes' => [
        'facultativo_15' => 0.15,
        'facultativo_30' => 0.30,
        'facultativo_total' => 0.45,
        'judicial_general' => 0.50,
    ],
    'clasificacion_subgrupos' => [
        'descuentos_legales' => [
            'bucket' => 'obligatorio',
            'label' => 'Obligatorio legal',
            'regla' => 'Fuera de topes 15/30/45',
            'prioridad' => 10,
        ],
        'resumen_remuneracional' => [
            'bucket' => 'informativo',
            'label' => 'Resumen remuneracional',
            'regla' => 'No es descuento aplicable',
            'prioridad' => 200,
        ],
        'redundante' => [
            'bucket' => 'ignorado',
            'label' => 'Redundante',
            'regla' => 'No aplica',
            'prioridad' => 200,
        ],
        'gremial' => [
            'bucket' => 'facultativo_15',
            'label' => 'Facultativo 15%',
            'regla' => 'Sujeto a acuerdo y tope 15%',
            'prioridad' => 80,
        ],
        'seguro' => [
            'bucket' => 'facultativo_15',
            'label' => 'Facultativo 15%',
            'regla' => 'Sujeto a acuerdo y tope 15%',
            'prioridad' => 80,
        ],
        'ahorro' => [
            'bucket' => 'facultativo_15',
            'label' => 'Facultativo 15%',
            'regla' => 'Ahorro general tratado como facultativo 15% salvo vivienda',
            'prioridad' => 70,
        ],
        'apv' => [
            'bucket' => 'facultativo_15',
            'label' => 'Facultativo 15%',
            'regla' => 'APV tratado como facultativo 15% en esta simulacion',
            'prioridad' => 70,
        ],
        'credito' => [
            'bucket' => 'facultativo_15',
            'label' => 'Facultativo 15%',
            'regla' => 'Credito general tratado como facultativo 15% salvo credito social CCAF',
            'prioridad' => 60,
        ],
        'administrativo' => [
            'bucket' => 'revision_manual',
            'label' => 'Revision manual',
            'regla' => 'Retenciones administrativas requieren validacion juridica interna',
            'prioridad' => 120,
        ],
        'salud_complementaria' => [
            'bucket' => 'facultativo_15',
            'label' => 'Facultativo 15%',
            'regla' => 'Sujeto a acuerdo y tope 15%',
            'prioridad' => 80,
        ],
        'judicial' => [
            'bucket' => 'judicial',
            'label' => 'Judicial',
            'regla' => 'Fuera de topes 15/30/45, con cap general 50% en esta simulacion',
            'prioridad' => 20,
        ],
        'reintegro' => [
            'bucket' => 'revision_manual',
            'label' => 'Revision manual',
            'regla' => 'Reintegros requieren clasificacion caso a caso',
            'prioridad' => 120,
        ],
        'cesantia' => [
            'bucket' => 'obligatorio',
            'label' => 'Obligatorio legal',
            'regla' => 'Descuento legal del trabajador; aporte empleador no aplica',
            'prioridad' => 15,
        ],
    ],
    'overrides_contains' => [
        [
            'field' => 'columna_origen',
            'contains' => 'VIVIENDA',
            'bucket' => 'facultativo_30',
            'label' => 'Facultativo 30%',
            'regla' => 'Destino vivienda/educacion/ahorro vivienda, sujeto a tope 30%',
            'prioridad' => 50,
        ],
        [
            'field' => 'columna_origen',
            'contains' => 'HIPOTEC',
            'bucket' => 'facultativo_30',
            'label' => 'Facultativo 30%',
            'regla' => 'Destino vivienda/educacion/ahorro vivienda, sujeto a tope 30%',
            'prioridad' => 50,
        ],
        [
            'field' => 'columna_origen',
            'contains' => 'EDUC',
            'bucket' => 'facultativo_30',
            'label' => 'Facultativo 30%',
            'regla' => 'Destino vivienda/educacion/ahorro vivienda, sujeto a tope 30%',
            'prioridad' => 50,
        ],
        [
            'field' => 'columna_origen',
            'contains' => 'CCAF',
            'contains_all' => ['CRED'],
            'bucket' => 'obligatorio',
            'label' => 'Obligatorio CCAF',
            'regla' => 'Credito social CCAF tratado como obligatorio',
            'prioridad' => 12,
        ],
        [
            'field' => 'campo_canonico',
            'contains' => 'ccaf',
            'contains_all' => ['credito'],
            'bucket' => 'obligatorio',
            'label' => 'Obligatorio CCAF',
            'regla' => 'Credito social CCAF tratado como obligatorio',
            'prioridad' => 12,
        ],
    ],
];
