<?php

return [
    [
        'value' => 'CL',
        'iso'   => 'cl',
        'abbr'  => 'CHL',
        'emoji' => '🇨🇱',
        'name'  => 'Chilena',
    ],
    [
        'value' => 'AR',
        'iso'   => 'ar',
        'abbr'  => 'ARG',
        'emoji' => '🇦🇷',
        'name'  => 'Argentina',
    ],
    [
        'value' => 'PE',
        'iso'   => 'pe',
        'abbr'  => 'PER',
        'emoji' => '🇵🇪',
        'name'  => 'Peruana',
    ],
    [
        'value' => 'BO',
        'iso'   => 'bo',
        'abbr'  => 'BOL',
        'emoji' => '🇧🇴',
        'name'  => 'Boliviana',
    ],
    [
        'value' => 'BR',
        'iso'   => 'br',
        'abbr'  => 'BRA',
        'emoji' => '🇧🇷',
        'name'  => 'Brasileña',
    ],
    [
        'value' => 'UY',
        'iso'   => 'uy',
        'abbr'  => 'URY',
        'emoji' => '🇺🇾',
        'name'  => 'Uruguaya',
    ],
    [
        'value' => 'PY',
        'iso'   => 'py',
        'abbr'  => 'PRY',
        'emoji' => '🇵🇾',
        'name'  => 'Paraguaya',
    ],
    [
        'value' => 'CO',
        'iso'   => 'co',
        'abbr'  => 'COL',
        'emoji' => '🇨🇴',
        'name'  => 'Colombiana',
    ],
    [
        'value' => 'VE',
        'iso'   => 've',
        'abbr'  => 'VEN',
        'emoji' => '🇻🇪',
        'name'  => 'Venezolana',
    ],
    [
        'value' => 'EC',
        'iso'   => 'ec',
        'abbr'  => 'ECU',
        'emoji' => '🇪🇨',
        'name'  => 'Ecuatoriana',
    ],
    [
        'value' => 'MX',
        'iso'   => 'mx',
        'abbr'  => 'MEX',
        'emoji' => '🇲🇽',
        'name'  => 'Mexicana',
    ],
    [
        'value' => 'ES',
        'iso'   => 'es',
        'abbr'  => 'ESP',
        'emoji' => '🇪🇸',
        'name'  => 'Española',
    ],
    [
        'value' => 'US',
        'iso'   => 'us',
        'abbr'  => 'USA',
        'emoji' => '🇺🇸',
        'name'  => 'Estadounidense',
    ],
    [
        'value' => 'IT',
        'iso'   => 'it',
        'abbr'  => 'ITA',
        'emoji' => '🇮🇹',
        'name'  => 'Italiana',
    ],
    [
        'value' => 'FR',
        'iso'   => 'fr',
        'abbr'  => 'FRA',
        'emoji' => '🇫🇷',
        'name'  => 'Francesa',
    ],
    [
        'value' => 'DE',
        'iso'   => 'de',
        'abbr'  => 'DEU',
        'emoji' => '🇩🇪',
        'name'  => 'Alemana',
    ],
    [
        'value' => 'CN',
        'iso'   => 'cn',
        'abbr'  => 'CHN',
        'emoji' => '🇨🇳',
        'name'  => 'China',
    ],
    [
        'value' => 'JP',
        'iso'   => 'jp',
        'abbr'  => 'JPN',
        'emoji' => '🇯🇵',
        'name'  => 'Japonesa',
    ],
    [
        'value' => 'KR',
        'iso'   => 'kr',
        'abbr'  => 'KOR',
        'emoji' => '🇰🇷',
        'name'  => 'Surcoreana',
    ],
];
