<?php

return [
    'captura' => [
        'enabled' => false,
        'ocr_driver' => (string) env('TRAMITES_OCR_DRIVER', 'auto'),
        'pdf_timeout_seconds' => (int) env('TRAMITES_PDF_TIMEOUT', 60),
        'ocr_timeout_seconds' => (int) env('TRAMITES_OCR_TIMEOUT', 180),
        'max_pages_ocr' => (int) env('TRAMITES_OCR_MAX_PAGES', 3),
        'ocr_dpi' => (int) env('TRAMITES_OCR_DPI', 96),
        'ocr_max_width' => (int) env('TRAMITES_OCR_MAX_WIDTH', 1400),
        'ocr_language' => (string) env('TRAMITES_OCR_LANGUAGE', 'spa+eng'),
        'python_bin' => (string) env('TRAMITES_OCR_PYTHON_BIN', '/home/slepac/venvs/tramites_ocr/bin/python'),
        'python_script' => (string) env('TRAMITES_OCR_SCRIPT', base_path('scripts/tramites_ocr_bridge.py')),
        'python_tmp_dir' => (string) env('TRAMITES_OCR_TMPDIR', '/home/slepac/tmp'),
        'min_text_length' => (int) env('TRAMITES_CAPTURE_MIN_TEXT_LENGTH', 120),
    ],

    'tipos' => [
        'reconocimiento_bienios' => [
            'label' => 'Reconocimiento de Bienios',
            'external_calculation' => true,
            'warning' => 'Adjunta documentos legibles, firmados y timbrados cuando corresponda. No debes ingresar fechas ni efectuar un cómputo en la plataforma; los períodos reconocibles serán determinados administrativamente durante la revisión.',
            'template_relative_path' => 'templates/CARTA BIENIOS.docx',
            'documentos' => [
                'carta_reconocimiento_director_ejecutivo' => [
                    'label' => 'Carta reconocimiento a director ejecutivo',
                    'multiple' => false,
                    'requires_period' => false,
                    'template_download' => true,
                    'required' => true,
                    'preload_on_create' => true,
                    'fixed_row' => true,
                    'show_add_button' => false,
                    'selectable_in_dynamic_rows' => false,
                    'capture_enabled' => false,
                ],
                'certificado_cotizaciones_afp_historico_tipo_b' => [
                    'label' => 'Certificado Cotizaciones AFP Histórico Tipo B con RUT de Empleador',
                    'multiple' => false,
                    'requires_period' => false,
                    'required' => true,
                    'preload_on_create' => true,
                    'fixed_row' => true,
                    'show_add_button' => false,
                    'selectable_in_dynamic_rows' => false,
                    'capture_enabled' => false,
                ],
                'certificado_antiguedad' => [
                    'label' => 'Certificado de Antigüedad',
                    'multiple' => true,
                    'requires_period' => false,
                    'required' => false,
                    'capture_enabled' => false,
                ],
                'contratos_trabajo' => [
                    'label' => 'Contratos de Trabajo',
                    'multiple' => true,
                    'requires_period' => false,
                    'required' => false,
                    'capture_enabled' => false,
                ],
                'decretos' => [
                    'label' => 'Decretos',
                    'multiple' => true,
                    'requires_period' => false,
                    'required' => false,
                    'capture_enabled' => false,
                ],
                'orden_trabajo' => [
                    'label' => 'Orden de Trabajo',
                    'multiple' => true,
                    'requires_period' => false,
                    'required' => false,
                    'capture_enabled' => false,
                ],
                'finiquitos' => [
                    'label' => 'Finiquitos',
                    'multiple' => true,
                    'requires_period' => false,
                    'required' => false,
                    'capture_enabled' => false,
                ],
                'nombramientos' => [
                    'label' => 'Nombramientos',
                    'multiple' => true,
                    'requires_period' => false,
                    'required' => false,
                    'capture_enabled' => false,
                ],
            ],
        ],
    ],
];
