@extends('layouts.app')
@section('content')
<div class="container py-4" data-votaciones-admin-jornada>
<div class="d-flex flex-wrap justify-content-between gap-3 align-items-start mb-4"><div><a href="{{ route('votaciones.admin.jornadas.index') }}" class="text-decoration-none">← Jornadas</a><h1 class="h3 mt-2 mb-1">{{ $jornada->nombre }}</h1><div class="text-muted">{{ $jornada->fecha->format('d-m-Y') }} · {{ $jornada->procesos->pluck('codigo')->join(' + ') }}</div></div><div class="d-flex flex-wrap gap-2">@if($jornada->publica)<a class="btn btn-outline-secondary" target="_blank" href="{{ route('public.votaciones.show',$jornada) }}">Vista pública</a>@endif @if($jornada->estado==='borrador')<a class="btn btn-outline-primary" href="{{ route('votaciones.admin.jornadas.edit',$jornada) }}">Editar</a><form method="POST" action="{{ route('votaciones.admin.jornadas.publicar',$jornada) }}">@csrf<button class="btn btn-success" onclick="return confirm('¿Publicar esta jornada?')">Publicar</button></form>@elseif($jornada->estado==='suspendida')<form method="POST" action="{{ route('votaciones.admin.jornadas.publicar',$jornada) }}">@csrf<button class="btn btn-success">Reanudar y publicar</button></form>@elseif(in_array($jornada->estado,['publicada','en_curso'],true))<form class="d-flex gap-2" method="POST" action="{{ route('votaciones.admin.jornadas.suspender',$jornada) }}">@csrf<input class="form-control" name="motivo" required placeholder="Motivo de suspensión"><button class="btn btn-outline-danger">Suspender</button></form>@endif</div></div>
@include('votaciones.partials.alertas')
<div class="row g-3 mb-4"><div class="col-md-3"><div class="card h-100"><div class="card-body"><small class="text-muted">Estado</small><div class="h5 mt-1">{{ str($jornada->estado)->replace('_',' ')->title() }}</div></div></div></div><div class="col-md-3"><div class="card h-100"><div class="card-body"><small class="text-muted">Grupos</small><div class="h5 mt-1">{{ $jornada->grupos->count() }}</div></div></div></div><div class="col-md-3"><div class="card h-100"><div class="card-body"><small class="text-muted">Establecimientos</small><div class="h5 mt-1">{{ $jornada->grupos->sum(fn($g)=>$g->rutas->count()) }}</div></div></div></div><div class="col-md-3"><div class="card h-100"><div class="card-body"><small class="text-muted">Incidencias abiertas</small><div class="h5 mt-1">{{ $jornada->incidencias->where('estado','abierta')->count() }}</div></div></div></div></div>

<div class="card shadow-sm mb-4"><div class="card-header d-flex flex-wrap justify-content-between gap-2"><strong>Previsualización de rutas</strong><span class="votaciones-admin-map-status" data-votaciones-admin-map-status></span></div><div class="card-body"><div class="votaciones-admin-map" data-votaciones-admin-map aria-label="Mapa de las rutas configuradas"></div></div></div>
<script type="application/json" id="votaciones-admin-rutas-data">{!! json_encode($mapaRutas, JSON_HEX_TAG|JSON_HEX_APOS|JSON_HEX_AMP|JSON_HEX_QUOT) !!}</script>

@if($jornada->estado==='borrador')
<div class="card shadow-sm mb-4"><div class="card-header"><strong>Crear grupo</strong></div><form method="POST" action="{{ route('votaciones.admin.grupos.store',$jornada) }}"><div class="card-body row g-3">@csrf<div class="col-md-2"><label class="form-label">Número</label><input class="form-control" type="number" min="1" name="numero" value="{{ old('numero',$jornada->grupos->max('numero')+1) }}" required></div><div class="col-md-4"><label class="form-label">Nombre</label><input class="form-control" name="nombre" value="{{ old('nombre') }}" placeholder="Grupo 1" required></div><div class="col-md-6"><label class="form-label">Responsable</label><select class="form-select" name="encargado_id" required><option value="">Seleccione</option>@foreach($usuarios as $u)<option value="{{ $u->id }}">{{ $u->display_name }} · {{ $u->email }}</option>@endforeach</select></div><div class="col-12"><label class="form-label">Otros integrantes</label><select class="form-select" name="miembros[]" multiple size="4">@foreach($usuarios as $u)<option value="{{ $u->id }}">{{ $u->display_name }} · {{ $u->email }}</option>@endforeach</select></div></div><div class="card-footer text-end"><button class="btn btn-primary">Crear grupo</button></div></form></div>
@endif

@forelse($jornada->grupos as $grupo)
<section class="card shadow-sm mb-4"><div class="card-header d-flex justify-content-between align-items-center"><div><strong>{{ $grupo->numero }}. {{ $grupo->nombre }}</strong><span class="badge text-bg-secondary ms-2">{{ str($grupo->estado)->replace('_',' ')->title() }}</span><div class="small text-muted">Responsable: {{ $grupo->encargado?->display_name ?? 'Sin asignar' }}</div></div><a class="btn btn-sm btn-outline-primary" href="{{ route('votaciones.operacion.show',$grupo) }}">Abrir operación</a></div>
<div class="card-body">
@if($jornada->estado==='borrador')<details class="mb-3"><summary class="link-primary">Editar grupo e integrantes</summary><form method="POST" action="{{ route('votaciones.admin.grupos.update',$grupo) }}" class="row g-2 mt-2">@csrf @method('PUT')<div class="col-md-2"><input class="form-control" type="number" name="numero" value="{{ $grupo->numero }}" required></div><div class="col-md-4"><input class="form-control" name="nombre" value="{{ $grupo->nombre }}" required></div><div class="col-md-6"><select class="form-select" name="encargado_id" required>@foreach($usuarios as $u)<option value="{{ $u->id }}" @selected($grupo->encargado_id===$u->id)>{{ $u->display_name }} · {{ $u->email }}</option>@endforeach</select></div><div class="col-12"><select class="form-select" name="miembros[]" multiple size="3">@foreach($usuarios as $u)<option value="{{ $u->id }}" @selected($grupo->miembros->contains($u))>{{ $u->display_name }} · {{ $u->email }}</option>@endforeach</select></div><div class="col-12 d-flex justify-content-between"><button class="btn btn-sm btn-primary">Guardar grupo</button></form><form method="POST" action="{{ route('votaciones.admin.grupos.destroy',$grupo) }}" onsubmit="return confirm('¿Eliminar el grupo y su ruta?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">Eliminar grupo</button></form></div></details>@endif
<div class="table-responsive"><table class="table table-sm align-middle"><thead><tr><th>Orden</th><th>Establecimiento</th><th>Comuna</th><th>Coordenadas</th><th>Estado</th><th></th></tr></thead><tbody>@forelse($grupo->rutas as $ruta)<tr><td>{{ $ruta->orden }}</td><td><strong>{{ $ruta->establecimiento->nombre_establecimiento }}</strong><br><small>RBD {{ $ruta->establecimiento->rbd }}</small></td><td>{{ $ruta->establecimiento->comuna }}</td><td>@if($coordenadasValidas->get($ruta->establecimiento_id, false))<span class="text-success">Válidas</span>@else<span class="text-danger fw-semibold">Faltantes o inválidas</span>@endif</td><td>{{ str($ruta->visita?->estado ?? 'pendiente')->replace('_',' ')->title() }}</td><td class="text-end">@if($jornada->estado==='borrador')<div class="btn-group"><form method="POST" action="{{ route('votaciones.admin.rutas.mover',$ruta) }}">@csrf @method('PATCH')<input type="hidden" name="direccion" value="subir"><button class="btn btn-sm btn-outline-secondary" title="Subir">↑</button></form><form method="POST" action="{{ route('votaciones.admin.rutas.mover',$ruta) }}">@csrf @method('PATCH')<input type="hidden" name="direccion" value="bajar"><button class="btn btn-sm btn-outline-secondary" title="Bajar">↓</button></form><form method="POST" action="{{ route('votaciones.admin.rutas.destroy',$ruta) }}">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger" title="Quitar" onclick="return confirm('¿Quitar de la ruta?')">×</button></form></div>@endif</td></tr>@empty<tr><td colspan="6" class="text-center text-muted">Ruta vacía.</td></tr>@endforelse</tbody></table></div>
@if($jornada->estado==='borrador')<form method="POST" action="{{ route('votaciones.admin.rutas.store',$grupo) }}" class="row g-2 align-items-end">@csrf<div class="col-md-10"><label class="form-label">Buscar y agregar establecimiento</label><input class="form-control mb-2" type="search" data-votacion-establecimiento-search placeholder="Buscar por nombre, RBD o comuna" autocomplete="off"><select class="form-select" name="establecimiento_id" data-votacion-establecimiento-select required><option value="">Seleccione</option>@foreach($establecimientos as $e)<option value="{{ $e->id }}" data-search="{{ $e->rbd }} {{ $e->nombre_establecimiento }} {{ $e->comuna }}" @disabled($grupo->rutas->contains('establecimiento_id',$e->id))>RBD {{ $e->rbd }} · {{ $e->nombre_establecimiento }} · {{ $e->comuna }}{{ $coordenadasValidas->get($e->id, false)?'':' · SIN COORDENADAS VÁLIDAS' }}</option>@endforeach</select></div><div class="col-md-2 d-grid"><button class="btn btn-outline-primary">Agregar</button></div></form>@endif
</div></section>
@empty<div class="alert alert-info">Aún no hay grupos configurados.</div>@endforelse

<div class="row g-4"><div class="col-lg-6"><div class="card shadow-sm"><div class="card-header"><strong>Incidencias</strong></div><div class="list-group list-group-flush">@forelse($jornada->incidencias as $i)<div class="list-group-item"><div class="d-flex justify-content-between"><strong>{{ config('votaciones.tipos_incidencia.'.$i->tipo,$i->tipo) }}</strong><span class="badge text-bg-{{ $i->estado==='abierta'?'warning':'success' }}">{{ ucfirst($i->estado) }}</span></div><div>{{ $i->descripcion }}</div><small class="text-muted">{{ $i->grupo?->nombre }} · {{ $i->publica?'Pública':'Interna' }}</small>@if($i->estado==='abierta' && auth()->user()->can('votaciones.admin'))<form class="d-flex gap-2 mt-2" method="POST" action="{{ route('votaciones.admin.incidencias.resolver',$i) }}">@csrf @method('PATCH')<input class="form-control form-control-sm" name="resolucion" required placeholder="Resolución"><button class="btn btn-sm btn-success">Resolver</button></form>@endif</div>@empty<div class="list-group-item text-muted">Sin incidencias.</div>@endforelse</div></div></div>
<div class="col-lg-6"><div class="card shadow-sm"><div class="card-header"><strong>Bitácora inmutable</strong></div><div class="list-group list-group-flush" style="max-height:420px;overflow:auto">@forelse($jornada->bitacora as $evento)<div class="list-group-item"><strong>{{ str($evento->evento)->replace('_',' ')->title() }}</strong><div>{{ $evento->descripcion }}</div><small class="text-muted">{{ $evento->created_at->timezone(config('votaciones.timezone'))->format('d-m-Y H:i:s') }} · {{ $evento->usuario?->display_name ?? 'Sistema' }}</small></div>@empty<div class="list-group-item text-muted">Sin eventos.</div>@endforelse</div></div></div></div>
@can('votaciones.admin')<div class="card border-warning mt-4"><div class="card-header"><strong>Corrección administrativa</strong></div><form method="POST" action="{{ route('votaciones.admin.jornadas.corregir',$jornada) }}"><div class="card-body row g-2">@csrf<div class="col-md-3"><select class="form-select" name="campo" required><option value="estado">Estado</option><option value="iniciada_at">Fecha/hora inicio</option><option value="finalizada_at">Fecha/hora término</option></select></div><div class="col-md-3"><input class="form-control" name="valor" required placeholder="Nuevo valor"></div><div class="col-md-4"><input class="form-control" name="motivo" required placeholder="Motivo obligatorio"></div><div class="col-md-2 d-grid"><button class="btn btn-warning">Corregir</button></div></div></form></div>@endcan
@can('votaciones.admin')
<div class="card border-warning mt-3"><div class="card-header"><strong>Corrección de una visita</strong></div><div class="card-body"><div class="accordion" id="correcciones-visita">
@foreach($jornada->grupos as $grupo)
@foreach($grupo->rutas as $ruta)
@if($ruta->visita)
<details class="border rounded p-2 mb-2"><summary>{{ $grupo->nombre }} · {{ $ruta->establecimiento->nombre_establecimiento }} · {{ str($ruta->visita->estado)->replace('_',' ')->title() }}</summary><form class="row g-2 mt-2" method="POST" action="{{ route('votaciones.admin.visitas.corregir',$ruta->visita) }}">@csrf<div class="col-md-3"><select class="form-select" name="campo"><option value="estado">Estado</option><option value="inicio_traslado_at">Inicio traslado</option><option value="inicio_votacion_at">Inicio votación</option><option value="fin_votacion_at">Fin votación</option></select></div><div class="col-md-3"><input class="form-control" name="valor" required placeholder="Nuevo valor"></div><div class="col-md-4"><input class="form-control" name="motivo" required placeholder="Motivo obligatorio"></div><div class="col-md-2 d-grid"><button class="btn btn-warning">Corregir</button></div></form></details>
@endif
@endforeach
@endforeach
</div></div></div>
@endcan
</div>
@endsection
@push('scripts')
@vite('resources/js/votaciones-admin-rutas.js')
@endpush
