@extends('layouts.app')

@push('styles')
    <style>
        .ip-show-hero,.ip-show-panel{border:1px solid #d9e4f3;border-radius:22px;background:#fff;box-shadow:0 14px 34px rgba(15,23,42,.06)}.ip-show-hero{padding:1.45rem 1.65rem;background:linear-gradient(135deg,#fff,#f0fdf4)}.ip-show-eyebrow{font-size:.78rem;font-weight:800;letter-spacing:.08em;text-transform:uppercase;color:#166534}.ip-show-title{font-size:1.75rem;font-weight:800;color:#0f172a;margin:.45rem 0}.ip-show-help{color:#475569;margin:0}.ip-show-pill{display:inline-flex;align-items:center;gap:.4rem;border-radius:999px;padding:.45rem .78rem;font-weight:800;font-size:.82rem}.ip-show-pill--solicitada{background:#fef3c7;color:#92400e}.ip-show-pill--resuelta{background:#dcfce7;color:#166534}.ip-show-actions{display:flex;flex-wrap:wrap;gap:.6rem}.ip-show-primary,.ip-show-secondary{border-radius:12px;min-height:43px;padding:.65rem .9rem;display:inline-flex;align-items:center;justify-content:center;gap:.45rem;font-weight:800;text-decoration:none}.ip-show-primary{background:#1d4ed8;border:1px solid #1d4ed8;color:#fff}.ip-show-primary:hover{background:#1e40af;color:#fff}.ip-show-secondary{background:#fff;border:1px solid #bfdbfe;color:#1d4ed8}.ip-show-secondary:hover{background:#eff6ff;color:#1e40af}.ip-show-stats{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:.85rem}.ip-show-stat{border:1px solid #dbe6f2;border-radius:17px;padding:1rem;background:#fff}.ip-show-stat__label{font-size:.75rem;font-weight:800;letter-spacing:.05em;text-transform:uppercase;color:#64748b}.ip-show-stat__value{font-size:1.5rem;font-weight:800;margin-top:.25rem}.ip-show-panel__head{padding:1.15rem 1.4rem;border-bottom:1px solid #e8eef5}.ip-show-table th{background:#f8fafc;color:#334155;font-size:.78rem;text-transform:uppercase;letter-spacing:.03em;padding:.8rem;white-space:nowrap}.ip-show-table td{padding:.85rem;vertical-align:middle;border-color:#e8eef5}.ip-show-name{font-weight:800;color:#0f172a}.ip-show-meta{font-size:.84rem;color:#64748b;margin-top:.18rem}.ip-show-state{display:inline-flex;align-items:center;gap:.35rem;border-radius:999px;padding:.34rem .62rem;font-size:.78rem;font-weight:800}.ip-show-state--solicitado{background:#fef3c7;color:#92400e}.ip-show-state--aceptado{background:#dcfce7;color:#166534}.ip-show-state--rechazado{background:#fee2e2;color:#b91c1c}.ip-import{background:#f8fbff;border-bottom:1px solid #dbeafe;padding:1rem 1.4rem}.ip-result-form{display:grid;grid-template-columns:minmax(130px,1fr) minmax(150px,1.8fr) auto;gap:.45rem;align-items:center;min-width:450px}@media(max-width:991px){.ip-show-stats{grid-template-columns:1fr}.ip-result-form{min-width:360px;grid-template-columns:1fr auto}.ip-result-form .ip-result-observation{grid-column:1/2}}@media(max-width:767px){.ip-show-hero{padding:1.2rem}.ip-show-actions a{flex:1}.ip-result-form{min-width:300px;grid-template-columns:1fr}.ip-result-form .ip-result-observation{grid-column:auto}}
    </style>
@endpush

@section('content')
    <div class="container py-4">
        <section class="ip-show-hero mb-4">
            <div class="d-flex flex-wrap justify-content-between align-items-start gap-3">
                <div><div class="ip-show-eyebrow"><i class="bi bi-shield-check"></i> Idoneidad psicológica AAEE</div><h1 class="ip-show-title">Solicitud #{{ $solicitud->id }}</h1><p class="ip-show-help">Período de ingreso: <strong>{{ optional($solicitud->fecha_inicio)->format('d-m-Y') }}</strong> al <strong>{{ optional($solicitud->fecha_termino)->format('d-m-Y') }}</strong>. Se genera desde el último padrón vigente disponible al crear esta nómina.</p></div>
                <span class="ip-show-pill ip-show-pill--{{ $solicitud->estado }}"><i class="bi {{ $solicitud->estado === 'resuelta' ? 'bi-check2-circle' : 'bi-hourglass-split' }}"></i>{{ \App\Models\IdoneidadPsicologicaSolicitud::ESTADOS[$solicitud->estado] ?? $solicitud->estado }}</span>
            </div>
            <div class="ip-show-actions mt-4"><a class="ip-show-secondary" href="{{ route('tramites.idoneidad-psicologica.index') }}"><i class="bi bi-arrow-left"></i> Volver</a><a class="ip-show-secondary" href="{{ route('tramites.idoneidad-psicologica.oficio.configurar', $solicitud) }}"><i class="bi bi-file-earmark-richtext"></i> Preparar oficio PDF</a><a class="ip-show-primary" href="{{ route('tramites.idoneidad-psicologica.plantilla-resultados', $solicitud) }}"><i class="bi bi-file-earmark-excel"></i> Descargar plantilla de resultados</a></div>
        </section>

        <div class="ip-show-stats mb-4"><div class="ip-show-stat"><div class="ip-show-stat__label">Pendientes</div><div class="ip-show-stat__value text-warning">{{ $conteos['solicitado'] }}</div><div class="small text-muted">Aún con estado Solicitado.</div></div><div class="ip-show-stat"><div class="ip-show-stat__label">Aceptados</div><div class="ip-show-stat__value text-success">{{ $conteos['aceptado'] }}</div><div class="small text-muted">Resultados favorables registrados.</div></div><div class="ip-show-stat"><div class="ip-show-stat__label">Rechazados</div><div class="ip-show-stat__value text-danger">{{ $conteos['rechazado'] }}</div><div class="small text-muted">Resultados no favorables registrados.</div></div></div>

        @if($solicitud->observacion)<div class="alert alert-info border-info-subtle"><strong>Observación del proceso:</strong> {{ $solicitud->observacion }}</div>@endif

        <section class="ip-show-panel">
            <div class="ip-show-panel__head"><h2 class="h5 fw-bold mb-1">Registro de resultados</h2><p class="text-muted mb-0 small">Actualiza un resultado en forma individual o carga la planilla Excel. La carga valida todos los RUT antes de efectuar cambios.</p></div>
            <div class="ip-import"><form method="POST" action="{{ route('tramites.idoneidad-psicologica.importar-resultados', $solicitud) }}" enctype="multipart/form-data" class="row g-2 align-items-end">@csrf<div class="col-lg-7"><label class="form-label fw-bold small" for="archivo">Carga masiva de resultados</label><input class="form-control @error('archivo') is-invalid @enderror" type="file" id="archivo" name="archivo" accept=".xlsx,.xls" required>@error('archivo')<div class="invalid-feedback d-block">{{ is_array($message) ? implode(' ', $message) : $message }}</div>@enderror</div><div class="col-lg-5"><button class="ip-show-primary w-100" type="submit"><i class="bi bi-upload"></i> Validar y aplicar Excel</button></div></form></div>
            <div class="table-responsive"><table class="table ip-show-table mb-0"><thead><tr><th>Funcionario</th><th>Establecimiento</th><th>Contrato</th><th>Fechas</th><th>Estado actual</th><th>Registrar resultado individual</th></tr></thead><tbody>
                @forelse($solicitud->funcionarios as $funcionario)
                    <tr><td><div class="ip-show-name">{{ $funcionario->nombre }}</div><div class="ip-show-meta">{{ $funcionario->rut }} · {{ $funcionario->estamento ?: 'Sin estamento' }} · {{ $funcionario->cargo_funcion ?: 'Sin cargo informado' }}</div></td><td><div class="fw-semibold">{{ $funcionario->establecimiento_nombre ?: 'Sin establecimiento' }}</div><div class="ip-show-meta">RBD {{ $funcionario->rbd ?: '—' }}</div></td><td>{{ $funcionario->tipo_contrato ?: 'Sin contrato informado' }}</td><td><div>Ingreso: {{ optional($funcionario->fecha_ingreso)->format('d-m-Y') ?: '—' }}</div><div class="ip-show-meta">Término: {{ optional($funcionario->fecha_termino)->format('d-m-Y') ?: 'Sin fecha' }}</div></td><td><span class="ip-show-state ip-show-state--{{ $funcionario->estado }}"><i class="bi {{ $funcionario->estado === 'aceptado' ? 'bi-check2-circle' : ($funcionario->estado === 'rechazado' ? 'bi-x-circle' : 'bi-hourglass-split') }}"></i>{{ \App\Models\IdoneidadPsicologicaFuncionario::ESTADOS[$funcionario->estado] ?? $funcionario->estado }}</span>@if($funcionario->resultado_registrado_at)<div class="ip-show-meta">Actualizado {{ $funcionario->resultado_registrado_at->format('d-m-Y H:i') }}</div>@endif</td><td><form method="POST" action="{{ route('tramites.idoneidad-psicologica.actualizar-funcionario', [$solicitud, $funcionario]) }}" class="ip-result-form">@csrf @method('PATCH')<select class="form-select form-select-sm" name="estado" aria-label="Estado para {{ $funcionario->nombre }}"><option value="aceptado" @selected($funcionario->estado === 'aceptado')>Aceptado</option><option value="rechazado" @selected($funcionario->estado === 'rechazado')>Rechazado</option></select><input class="form-control form-control-sm ip-result-observation" name="observacion_resultado" maxlength="2000" value="{{ $funcionario->observacion_resultado }}" placeholder="Observación opcional"><button class="ip-show-primary btn-sm" type="submit"><i class="bi bi-save"></i> Guardar</button></form></td></tr>
                @empty
                    <tr><td colspan="6" class="text-center text-muted py-4">La solicitud no contiene funcionarios.</td></tr>
                @endforelse
            </tbody></table></div>
        </section>
    </div>
@endsection
